# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xtz3h4dLB4xAEaTJ0zlwpMF8KZLTA1fm

Question 4

01-13:  Heart

---


14-26:  Diamond

---


27-39:  Spade

---


40-52:  Clover
"""

import random

def display_card(a,j):
  i=a[j]
  if i in range(1,14):
    if i==11:
      print('Heart : Jack')
    elif i==12:
      print('Heart : Queen')
    elif i==13:
      print('Heart : King')
    elif i==1:
      print('Heart : Ace')
    else:
      print('Heart :',i)

  elif i in range(14,27):
    if i==24:
      print('Diamond : Jack')
    elif i==25:
      print('Diamond : Queen')
    elif i==26:
      print('Diamond : King')
    elif i==14:
      print('Diamond : Ace')
    else:
      print('Diamond :',i%13)

  elif i in range(27,40):
    if i==37:
      print('Spade : Jack')
    elif i==38:
      print('Spade : Queen')
    elif i==39:
      print('Spade : King')
    elif i==27:
      print('Spade : Ace')
    else:
      print('Spade :',i%13)

  else:
    if i==50:
      print('Clover : Jack')
    elif i==51:
      print('Clover : Queen')
    elif i==52:
      print('Clover : King')
    elif i==40:
      print('Clover : Ace')
    else:
      print('Clover :',i%13)
  return i

a=random.sample(range(1, 52), 8)
p=0
for j in range(0,7):
  x=0
  y=0
  k=display_card(a,j)
  l=input("Enter Prediction (Higher or Lower): ")
  if k%13==0:
      x=13
  if a[j+1]%13==0:
      y=13
  if l=='H':
    if k%13+x<a[j+1]%13+y:
      p=p+20
      print('Correct')
    else:
      p=p-15
      print('Incorrect')
  else:
    if k%13+x>a[j+1]%13+y:
      p=p+20
      print('Correct')
    else:
      p=p-15
      print('Incorrect')
  print('Your Current Score is: ',p)
print('Your Total Score is: ',p)

